org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false
# Plugin Metadata
plugin_group=pilouface
plugin_description=A mod that let you fly around !
plugin_author=PilouFace
plugin_website=https://github.com/Pilou26021
plugin_main_entrypoint=com.pilouface.aerial.Aerial
server_version=*
